#!/bin/bash

# Create the complete fraud detection system directory structure

BASE_DIR="/Users/parthbatwara/Desktop/Code/credit-card-fraud-detection"

echo "Creating fraud detection system directory structure..."

# Create all directories
mkdir -p "$BASE_DIR/services/api/app/dependencies"
mkdir -p "$BASE_DIR/services/inference/app/models"
mkdir -p "$BASE_DIR/services/inference/app/features"
mkdir -p "$BASE_DIR/services/inference/app/consumers"
mkdir -p "$BASE_DIR/services/inference/app/utils"
mkdir -p "$BASE_DIR/services/inference/tests"
mkdir -p "$BASE_DIR/services/enricher/app/enrichers"
mkdir -p "$BASE_DIR/services/enricher/app/consumers"
mkdir -p "$BASE_DIR/services/enricher/app/utils"
mkdir -p "$BASE_DIR/services/enricher/tests"
mkdir -p "$BASE_DIR/services/trainer/app/trainers"
mkdir -p "$BASE_DIR/services/trainer/app/evaluation"
mkdir -p "$BASE_DIR/services/trainer/app/data"
mkdir -p "$BASE_DIR/services/trainer/app/pipeline"
mkdir -p "$BASE_DIR/services/trainer/tests"
mkdir -p "$BASE_DIR/services/graph-builder/app/builders"
mkdir -p "$BASE_DIR/services/graph-builder/app/consumers"
mkdir -p "$BASE_DIR/services/graph-builder/app/utils"
mkdir -p "$BASE_DIR/services/graph-builder/tests"
mkdir -p "$BASE_DIR/services/simulator/app/generators"
mkdir -p "$BASE_DIR/services/simulator/app/data"
mkdir -p "$BASE_DIR/services/simulator/app/utils"
mkdir -p "$BASE_DIR/services/simulator/tests"
mkdir -p "$BASE_DIR/services/dashboard/public"
mkdir -p "$BASE_DIR/services/dashboard/src/components/common"
mkdir -p "$BASE_DIR/services/dashboard/src/components/dashboard"
mkdir -p "$BASE_DIR/services/dashboard/src/components/transactions"
mkdir -p "$BASE_DIR/services/dashboard/src/components/explanations"
mkdir -p "$BASE_DIR/services/dashboard/src/components/models"
mkdir -p "$BASE_DIR/services/dashboard/src/components/drift"
mkdir -p "$BASE_DIR/services/dashboard/src/components/alerts"
mkdir -p "$BASE_DIR/services/dashboard/src/services"
mkdir -p "$BASE_DIR/services/dashboard/src/hooks"
mkdir -p "$BASE_DIR/services/dashboard/src/utils"
mkdir -p "$BASE_DIR/services/dashboard/src/styles/components"
mkdir -p "$BASE_DIR/services/dashboard/tests"
mkdir -p "$BASE_DIR/shared/schemas"
mkdir -p "$BASE_DIR/shared/utils"
mkdir -p "$BASE_DIR/shared/constants"
mkdir -p "$BASE_DIR/scripts"
mkdir -p "$BASE_DIR/config/kafka"
mkdir -p "$BASE_DIR/config/neo4j"
mkdir -p "$BASE_DIR/config/nginx"
mkdir -p "$BASE_DIR/config/prometheus"
mkdir -p "$BASE_DIR/data/sample"
mkdir -p "$BASE_DIR/data/models"
mkdir -p "$BASE_DIR/data/embeddings"
mkdir -p "$BASE_DIR/notebooks"
mkdir -p "$BASE_DIR/monitoring/grafana/dashboards"
mkdir -p "$BASE_DIR/monitoring/grafana/provisioning/dashboards"
mkdir -p "$BASE_DIR/monitoring/grafana/provisioning/datasources"
mkdir -p "$BASE_DIR/monitoring/alerts"
mkdir -p "$BASE_DIR/docs"
mkdir -p "$BASE_DIR/tests/integration"
mkdir -p "$BASE_DIR/tests/performance"
mkdir -p "$BASE_DIR/tests/fixtures/model_artifacts"

echo "Directory structure created successfully!"
echo "Total directories created: $(find $BASE_DIR -type d | wc -l)"
